version: '3.9'

services:
  prometheus:
    image: prom/prometheus

    ports:
      - "19090:9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana

    ports:
      - "13001:3000"

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  tempo:
    image: grafana/tempo

    command: [ "-config.file=/etc/tempo.yml" ]

    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yml

    ports:
      - "13200:3200"
      - "14317:4317"
      - "14318:4318"