version: '3.9'

services:
  prometheus:
    image: prom/prometheus

    ports:
      - "9090:9090"

    volumes:
      - ../telegram-support-observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana

    ports:
      - "3001:3000"

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

    volumes:
      - ../telegram-support-observability/grafana/provisioning:/etc/grafana/provisioning
      - ../telegram-support-observability/grafana/dashboards:/var/lib/grafana/dashboards

  tempo:
    image: grafana/tempo

    command: [ "-config.file=/etc/tempo.yml" ]

    volumes:
      - ../telegram-support-observability/tempo/tempo.yml:/etc/tempo.yml

    ports:
      - "3200:3200"
      - "4318:4318"